/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assurtonkaz;




import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfWriter;
import com.mycompany.assurtonkaz.AddClient;
import static com.mycompany.assurtonkaz.AddClient.MailInput;
import static com.mycompany.assurtonkaz.AddClient.NomInput;
import static com.mycompany.assurtonkaz.AddClient.PrenomInput;
import static com.mycompany.assurtonkaz.AddClient.TelInput;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import models.Client;
import models.ListReponse;
import models.m_Connexion;
/**
 *
 * @author manu
 */
public class Question extends javax.swing.JFrame {
   
    
    
    
    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();
    }
    
    public Question(Client client) {
        initComponents();
        jframe_Acc6.setVisible(false);
        jframe_Piece.setVisible(false);
        jframe_Jard.setVisible(false);
        jframe_exp.setVisible(false);
        Lr.setClient(client);
    }
    
//    public Question(Integer idClient) {
//        initComponents();
//        jframe_Acc6.setVisible(false);
//        jframe_Piece.setVisible(false);
//        jframe_Jard.setVisible(false);
//        jframe_exp.setVisible(false);
//        Lr.setIdClientCont(idClient);
//        System.out.println(idClient);
//    }
    
    ListReponse Lr = new ListReponse();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAcc = new javax.swing.ButtonGroup();
        btnGroupAss = new javax.swing.ButtonGroup();
        btnGroupMais = new javax.swing.ButtonGroup();
        btnGroupJard = new javax.swing.ButtonGroup();
        btnGroupVoit = new javax.swing.ButtonGroup();
        btnGroupTele = new javax.swing.ButtonGroup();
        exportPDF = new javax.swing.JFileChooser();
        jframe_Acc6 = new javax.swing.JInternalFrame();
        jLabel15 = new javax.swing.JLabel();
        btnAcc = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        rBtnOuiAcc = new javax.swing.JRadioButton();
        rBtnNonAcc = new javax.swing.JRadioButton();
        jframe_ASS = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        rBtnOuiAssur = new javax.swing.JRadioButton();
        rBtnNonAssur = new javax.swing.JRadioButton();
        btnAssur = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jframe_Piece = new javax.swing.JInternalFrame();
        jLabel18 = new javax.swing.JLabel();
        nbrPiece = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        rBtnOuiEtage = new javax.swing.JRadioButton();
        rbtnNonEtage = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        nbrEtage = new javax.swing.JSpinner();
        btnInfHouse = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jframe_exp = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        btnPdf = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jframe_Jard = new javax.swing.JInternalFrame();
        jLabel21 = new javax.swing.JLabel();
        rBtnOuiJard = new javax.swing.JRadioButton();
        rBtnNonJar = new javax.swing.JRadioButton();
        rBtnOuiVoiture = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rBtnNonVoiture = new javax.swing.JRadioButton();
        rBtnNonTele = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rBtnOuiTele = new javax.swing.JRadioButton();
        jButton16 = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jframe_Acc6.setVisible(true);

        jLabel15.setText("Vivez-vous seul(e) ?");

        btnAcc.setText("Suivant");
        btnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccActionPerformed(evt);
            }
        });

        jButton8.setText("Retour");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnGroupAcc.add(rBtnOuiAcc);
        rBtnOuiAcc.setText("Oui");

        btnGroupAcc.add(rBtnNonAcc);
        rBtnNonAcc.setText("Non");

        javax.swing.GroupLayout jframe_Acc6Layout = new javax.swing.GroupLayout(jframe_Acc6.getContentPane());
        jframe_Acc6.getContentPane().setLayout(jframe_Acc6Layout);
        jframe_Acc6Layout.setHorizontalGroup(
            jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_Acc6Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_Acc6Layout.createSequentialGroup()
                        .addGroup(jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jframe_Acc6Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jframe_Acc6Layout.createSequentialGroup()
                                .addComponent(rBtnOuiAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rBtnNonAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_Acc6Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jframe_Acc6Layout.setVerticalGroup(
            jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_Acc6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiAcc)
                    .addComponent(rBtnNonAcc))
                .addGap(39, 39, 39)
                .addGroup(jframe_Acc6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(btnAcc))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jframe_ASS.setVisible(true);

        jLabel17.setText("Êtiez-vous assuré avant de venir vers nous ?");

        btnGroupAss.add(rBtnOuiAssur);
        rBtnOuiAssur.setText("Oui");

        btnGroupAss.add(rBtnNonAssur);
        rBtnNonAssur.setText("Non");

        btnAssur.setText("Suivant");
        btnAssur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssurActionPerformed(evt);
            }
        });

        jMenu3.setText("Réponses");

        jMenuItem2.setText("Voir réponses");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jframe_ASS.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jframe_ASSLayout = new javax.swing.GroupLayout(jframe_ASS.getContentPane());
        jframe_ASS.getContentPane().setLayout(jframe_ASSLayout);
        jframe_ASSLayout.setHorizontalGroup(
            jframe_ASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_ASSLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jframe_ASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_ASSLayout.createSequentialGroup()
                        .addComponent(rBtnOuiAssur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rBtnNonAssur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_ASSLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap())))
            .addGroup(jframe_ASSLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAssur, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jframe_ASSLayout.setVerticalGroup(
            jframe_ASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_ASSLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addGroup(jframe_ASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiAssur)
                    .addComponent(rBtnNonAssur))
                .addGap(48, 48, 48)
                .addComponent(btnAssur)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jframe_Piece.setVisible(true);

        jLabel18.setText("Combien de pièce disposez vous dans votre maison ?");

        jLabel19.setText("Avez-vous un ou plusieur étage(s) ?");

        btnGroupMais.add(rBtnOuiEtage);
        rBtnOuiEtage.setText("Oui");

        btnGroupMais.add(rbtnNonEtage);
        rbtnNonEtage.setText("Non");

        jLabel20.setText("Combien d'étage ?");

        btnInfHouse.setText("Suivant");
        btnInfHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfHouseActionPerformed(evt);
            }
        });

        jButton11.setText("Retour");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframe_PieceLayout = new javax.swing.GroupLayout(jframe_Piece.getContentPane());
        jframe_Piece.getContentPane().setLayout(jframe_PieceLayout);
        jframe_PieceLayout.setHorizontalGroup(
            jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_PieceLayout.createSequentialGroup()
                .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jframe_PieceLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnInfHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jframe_PieceLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(rBtnOuiEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnNonEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addGroup(jframe_PieceLayout.createSequentialGroup()
                .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(nbrPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel20))
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(nbrEtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jframe_PieceLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jframe_PieceLayout.setVerticalGroup(
            jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_PieceLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbrPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiEtage)
                    .addComponent(rbtnNonEtage))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbrEtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jframe_PieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(btnInfHouse))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jframe_exp.setVisible(true);

        jLabel1.setText("Exporter");

        btnPdf.setText("PDF");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        jButton13.setText(".txt");

        jButton14.setText("Les deux");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Retour");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframe_expLayout = new javax.swing.GroupLayout(jframe_exp.getContentPane());
        jframe_exp.getContentPane().setLayout(jframe_expLayout);
        jframe_expLayout.setHorizontalGroup(
            jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_expLayout.createSequentialGroup()
                .addGroup(jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_expLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jframe_expLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jframe_expLayout.createSequentialGroup()
                                .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jframe_expLayout.createSequentialGroup()
                        .addGroup(jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jframe_expLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1))
                            .addGroup(jframe_expLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jframe_expLayout.setVerticalGroup(
            jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_expLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jframe_expLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPdf)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jframe_Jard.setVisible(true);

        jLabel21.setText("Avez-vous un jardin ?");

        btnGroupJard.add(rBtnOuiJard);
        rBtnOuiJard.setText("Oui");

        btnGroupJard.add(rBtnNonJar);
        rBtnNonJar.setText("Non");

        btnGroupVoit.add(rBtnOuiVoiture);
        rBtnOuiVoiture.setText("Oui");

        jLabel22.setText("Si oui, avez-vous une voiture ?");

        btnGroupVoit.add(rBtnNonVoiture);
        rBtnNonVoiture.setText("Non");

        btnGroupTele.add(rBtnNonTele);
        rBtnNonTele.setText("Non");

        jLabel23.setText("Avez-vous une télévision ?");

        btnGroupTele.add(rBtnOuiTele);
        rBtnOuiTele.setText("Oui");

        jButton16.setText("Retour");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        btnDetail.setText("Enregistrer");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframe_JardLayout = new javax.swing.GroupLayout(jframe_Jard.getContentPane());
        jframe_Jard.getContentPane().setLayout(jframe_JardLayout);
        jframe_JardLayout.setHorizontalGroup(
            jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_JardLayout.createSequentialGroup()
                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_JardLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_JardLayout.createSequentialGroup()
                                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jframe_JardLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jframe_JardLayout.createSequentialGroup()
                                                .addComponent(rBtnOuiVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rBtnNonVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jframe_JardLayout.createSequentialGroup()
                                                .addComponent(rBtnOuiTele, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rBtnNonTele, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_JardLayout.createSequentialGroup()
                                .addComponent(rBtnOuiJard, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rBtnNonJar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jframe_JardLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnDetail)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jframe_JardLayout.setVerticalGroup(
            jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_JardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addGap(1, 1, 1)
                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiJard)
                    .addComponent(rBtnNonJar))
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addGap(10, 10, 10)
                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiVoiture)
                    .addComponent(rBtnNonVoiture))
                .addGap(31, 31, 31)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnOuiTele)
                    .addComponent(rBtnNonTele))
                .addGap(30, 30, 30)
                .addGroup(jframe_JardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(btnDetail))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jframe_Jard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jframe_Acc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jframe_ASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jframe_Piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jframe_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jframe_Acc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jframe_ASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jframe_Jard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jframe_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jframe_Piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnAssurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssurActionPerformed
        
        jframe_ASS.setVisible(false);
        jframe_Acc6.setVisible(true);
        if (rBtnOuiAssur.isSelected())
        {
            Lr.setIsAssure(true);
        }
        else
        {
            Lr.setIsAssure(false);
        }
        System.out.println(Lr.getIsAssure());
        
    }//GEN-LAST:event_btnAssurActionPerformed

    private void btnInfHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfHouseActionPerformed
        jframe_Piece.setVisible(false);
        jframe_Jard.setVisible(true);
        Lr.setNbPiece((int) nbrPiece.getValue());
        if (rBtnOuiEtage.isSelected())
        {
            Lr.setIsFloor(true);
        }
        else
        {
             Lr.setIsFloor(false);
        }
        Lr.setNbFloor((int) nbrEtage.getValue());
        System.out.println(Lr.getNbPiece());
        System.out.println(Lr.getIsFloor());
        System.out.println(Lr.getIsFloor());
    }//GEN-LAST:event_btnInfHouseActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jframe_Acc6.setVisible(true);
        jframe_Piece.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jframe_Jard.setVisible(true);
        jframe_exp.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jframe_Piece.setVisible(true);
        jframe_Jard.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        //Save in BDD
        jframe_Jard.setVisible(false);
        jframe_exp.setVisible(true);
        if(rBtnOuiJard.isSelected())
        {
            Lr.setIsGarden(true);
        }
        else
        {
            Lr.setIsGarden(false );
        }
        if(rBtnOuiVoiture.isSelected())
        {
            Lr.setIsCar(true);
        }
        else
        {
            Lr.setIsCar(false);
        }
        if(rBtnOuiTele.isSelected())
        {
            Lr.setIsTv(true);
        }
        else
        {
            Lr.setIsTv(false);
        }
        System.out.println(Lr.getIsGarden());
        System.out.println(Lr.getIsCar());
        System.out.println(Lr.getIsTv());
        
        Connection co = m_Connexion.connexion();
        int count;
        try {
            Statement st = co.createStatement();
            
            

            PreparedStatement pst = co.prepareStatement("INSERT INTO public.\"Contrat\" VALUES (?,?,?,?,?,?,?,?,?)");
            pst.setBoolean(1, Lr.getIsAssure());
            pst.setBoolean(2, Lr.getIsAlone());
            pst.setInt(3, Lr.getNbPiece());
            pst.setInt(4, Lr.getNbFloor());
            pst.setBoolean(5, Lr.getIsFloor());
            pst.setBoolean(6, Lr.getIsGarden());
            pst.setBoolean(7, Lr.getIsCar());
            pst.setBoolean(8, Lr.getIsTv());
            pst.setInt(9, Lr.getClient().getIdClient());
           
            pst.executeUpdate();
            pst.close();
//            notifier();
        } catch (SQLException ex) {
            Logger.getLogger(AddClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        System.out.println(Lr.toString()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AffReponse rep = new AffReponse(Lr);
        Lr.ajouterObser(rep);
        rep.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jframe_ASS.setVisible(true);// TODO add your handling code here:
        jframe_Acc6.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
        jframe_Acc6.setVisible(false);
        jframe_Piece.setVisible(true);
        if(rBtnOuiAcc.isSelected())
        {
            Lr.setIsAlone(true);
        }
        else
        {
            Lr.setIsAlone(false);
        }
        
        
        System.out.println(Lr.getIsAlone());
    }//GEN-LAST:event_btnAccActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        
        String path ="";
        JFileChooser ex= new JFileChooser();
        ex.setVisible(true);
        ex.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = ex.showSaveDialog(this);
        
        if(x==JFileChooser.APPROVE_OPTION)
        {
            path =ex.getSelectedFile().getPath();
        }
        
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("contrat"+ Lr.getClient().getNomClient()+ Lr.getClient().getPrenomClient() +".pdf"));
            document.open();
            Font font = FontFactory.getFont(FontFactory.COURIER, 16, BaseColor.BLACK);
            Chunk chunk = new Chunk("Hello World", font);
            document.add(chunk);
        document.close();
        } catch (FileNotFoundException ex1) {
            Logger.getLogger(Question.class.getName()).log(Level.SEVERE, null, ex1);
        } catch (DocumentException ex1) {
            Logger.getLogger(Question.class.getName()).log(Level.SEVERE, null, ex1);
        }

        

        
    }//GEN-LAST:event_btnPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Question().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnAssur;
    private javax.swing.JButton btnDetail;
    private javax.swing.ButtonGroup btnGroupAcc;
    private javax.swing.ButtonGroup btnGroupAss;
    private javax.swing.ButtonGroup btnGroupJard;
    private javax.swing.ButtonGroup btnGroupMais;
    private javax.swing.ButtonGroup btnGroupTele;
    private javax.swing.ButtonGroup btnGroupVoit;
    private javax.swing.JButton btnInfHouse;
    private javax.swing.JButton btnPdf;
    private javax.swing.JFileChooser exportPDF;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JInternalFrame jframe_ASS;
    private javax.swing.JInternalFrame jframe_Acc6;
    private javax.swing.JInternalFrame jframe_Jard;
    private javax.swing.JInternalFrame jframe_Piece;
    private javax.swing.JInternalFrame jframe_exp;
    private javax.swing.JSpinner nbrEtage;
    private javax.swing.JSpinner nbrPiece;
    private javax.swing.JRadioButton rBtnNonAcc;
    private javax.swing.JRadioButton rBtnNonAssur;
    private javax.swing.JRadioButton rBtnNonJar;
    private javax.swing.JRadioButton rBtnNonTele;
    private javax.swing.JRadioButton rBtnNonVoiture;
    private javax.swing.JRadioButton rBtnOuiAcc;
    private javax.swing.JRadioButton rBtnOuiAssur;
    private javax.swing.JRadioButton rBtnOuiEtage;
    private javax.swing.JRadioButton rBtnOuiJard;
    private javax.swing.JRadioButton rBtnOuiTele;
    private javax.swing.JRadioButton rBtnOuiVoiture;
    private javax.swing.JRadioButton rbtnNonEtage;
    // End of variables declaration//GEN-END:variables
}
